version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  volumes:
  sr-db:

  producer:
    volumes:
      - sr-db:/app/data
    build: ./producer-server
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis:6379
    depends_on:
      - kafka
      - redis
    restart: unless-stopped

  consumer:
    volumes:
      - sr-db:/app/data
    build: ./consumer-server
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis:6379
      - ESRGAN_ENGINE_URL=http://esrgan-engine:7001
    depends_on:
      - kafka
      - redis
      - esrgan-engine
    restart: unless-stopped

  esrgan-engine:
    build: ./esrgan-engine
    ports:
      - "7001:7001"
    environment:
      - PORT=7001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/"]
      interval: 10s
      timeout: 5s
      retries: 5
